name: pinocchio
channels:
  - conda-forge
dependencies:
  - eigen=3.4.0
  - hpp-fcl
  - numpy
  - boost
  - eigenpy
  - urdfdom
  - python
  - cmake
  - ccache
  - pkg-config
  - ninja
  - llvm-openmp
  - cxx-compiler
  - meshcat-python
  - casadi
  - cppad<=20230000
  - cppadcodegen
  - pycppad
  - matplotlib
  - mpfr
  - qhull
  - qhull-static
  - libsdformat
